language: go
go:
  - 1.4.2
#before_install:
# - sudo apt-get install -qq libedit-dev
install:
- go get github.com/gwenn/yacr
- go get -tags readline github.com/gwenn/goreadline
before_script:
 - go get github.com/bmizerany/assert
script:
 - go test -v -tags readline github.com/gwenn/goreadline